version: "3.8"
services:
  backend:
    image: gradle:8.3.0-jdk17
    working_dir: /app
    expose:
      - 80
    networks:
      - backend
    volumes:
      - ./backend:/app
  sql:
    image: mcr.microsoft.com/mssql/server:2022-CU7-ubuntu-20.04
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password123"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    expose:
      - 1433
    networks:
      - backend
    # volumes:
    #   - ./:/docker-entrypoint-initdb.d
  frontend:
    image: node:20.0.0
    working_dir: /app
    expose:
      - 80
    networks:
      - backend
      - default
    volumes:
      - ./frontend:/app

networks:
  backend: