version: "3.8"
services:
  backend:
    build: ./backend
    expose:
      - 80
    networks:
      - backend
  sql:
    image: mysql:8.1.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: api
      MYSQL_USER: api
      MYSQL_PASSWORD: 123456789
    ports:
      - expose
    networks:
      - backend

networks:
  backend: