version: "3.8"
services:
  backend:
    image: gradle:8.3.0-jdk17
    working_dir: /app
    ports:
      - "80:80"
    expose:
      - 80
    volumes:
      - ./backend:/app
    command: gradle bootRun

  sql:
    image: mcr.microsoft.com/mssql/server:2022-CU7-ubuntu-20.04
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password123"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    expose:
      - 1433
    volumes:
      - db:/var/opt/mssql
  frontend:
    image: node:20.0.0
    working_dir: /app
    volumes:
      - ./frontend:/app

volumes:
  db: